# actions/checkout v7.0.1: 3d3c42e5aac5ba805825da76410c181273ba90b1
# actions/setup-go v7.0.0: b7ad1dad31e06c5925ef5d2fc7ad053ef454303e

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: go.mod

      - name: Install tools
        run: make install-tools

      - name: Lint
        run: make lint

      - name: Test
        run: make test
